version: 2

project_name: ddev-mngr

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

brews:
  - name: ddev-mngr
    repository:
      owner: dkd-dobberkau
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/dkd-dobberkau/ddev-mngr"
    description: "CLI tool to manage DDEV projects with interactive TUI"
    license: "Apache-2.0"
    install: |
      bin.install "ddev-mngr"
    test: |
      system "#{bin}/ddev-mngr", "--help"
